#Fichier: inventory/group_vars/borderleafs.yml

---
# Variables sp√©cifiques aux Border Leafs
bgp_asn: 65200  # Base ASN, sera override par host_vars

# Interfaces vers l'externe
firewall_interfaces:
  - { name: "swp3.1", ip: "169.254.254.7/31", vrf: "default" }
  - { name: "swp3.2", ip: "169.254.254.9/31", vrf: "evpn-vrf" }
  - { name: "swp3.3", ip: "169.254.254.11/31", vrf: "internet-vrf" }

router_interface:
  - { name: "bond1.1", ip: "169.254.127.3/31", vrf: "internet-vrf" }

peer_group_names:
  underlay: "underlay"
  internet: "INTERNET"