#Fichier: inventory/group_vars/spines.yml

---
# Variables sp√©cifiques aux Spines
spine_asn_base: 65000
spine_interfaces:
  - { name: "swp1", description: "vers LEAF11" }
  - { name: "swp2", description: "vers LEAF21" } 
  - { name: "swp3", description: "vers LEAF12" }
  - { name: "swp4", description: "vers LEAF22" }
  - { name: "swp5", description: "vers BLEAF10" }
  - { name: "swp6", description: "vers BLEAF11" }

peer_group_name: "UNDERLAY"